package com.marcelus.uristringbuilder.available.uri.schemes;

/*
Enum created based on this WIKIPEDIA page: https://en.wikipedia.org/wiki/List_of_URI_schemes
 */

import java.util.Arrays;

public enum URISchemes {
    ADMIN("admin"),
    APP("app"),
    JAVASCRIPT("javascript"),
    JDBC("jdbc"),
    MICROSOFT_TEAMS("msteams"),
    OPEN_DATABASE("odbc"),
    DIAMETER_PROTOCOL("aaa"),
    DIAMETER_PROTOCOL2("aaas"),
    PRODUCT_AND_INTERNAL_INFORMATION("about"),
    APPLICATION_CONFIGURATION_ACCESS_PROTOCOL("acap"),
    IDENTIFYING_USER_ACCOUNT("acct"),
    ANONYMOUS_CUSTOMER_REFERENCE("acr"),
    ADIUM_XTRAS_INSTALLATION("adiumxtra"),
    APPLE_FILING_PROTOCOL("afp"),
    ANDREW_FILE_SYSTEM("afs"),
    AOL_INSTANT_MESSENGER("aim"),
    APT_INSTALLATION_SOFTWARE("apt"),
    MHTML("attachment"),
    ACTIVE_WORLDS_WORLD("aw"),
    AMSS_BROADCAST_IDENTIFIER("amss"),
    BARION("barion"),
    BESHARE("beshare"),
    BITCOIN("bitcoin"),
    BINARY_DATA_ACCESS("blob"),
    BOLO_GAME_PROTOCOL("bolo"),
    SKYPE("callto"),
    SKYPE2("skype"),
    CALENDAR_ACCESS_PROTOCOL("cap"),
    CHROME("chrome"),
    CHROME_EXTENSIONS("chrome-extension"),
    SMPT_MINE_INDIVIDUAL_PARTS("cid"),
    CONSTRAINED_APPLICATION_PROTOCOL("coap"),
    CONSTRAINED_APPLICATION_PROTOCOL2("coaps"),
    ANDROID_CONTENT_PROVIDER("content"),
    TV_ANYTIME_CONTENT_REFERENCE_IDENTIFIER("crid"),
    CONCURRENT_VERSIONS_SYSTEM("cvs"),
    DAB_BROADCAST("dab"),
    DATA_ITEMS_INLINE("data"),
    WEBDAV("dav"),
    DICTIONARY_SERVICE_PROTOCOL("dict"),
    DOMAIN_NAME_SYSTEM("dns"),
    DIRECT_NETWORK_TRANSFER_PROTOCOL("dntp"),
    DIGITAL_OBJECT_IDENTIFIER("doi"),
    DRM_BROADCAST("drm"),
    DTNRG("dtn"),
    DVB("dvb"),
    E_DONKEY_2000("ed2k"),
    EXAMPLES("example"),
    APPLE_FACETIME("facetime"),
    FAX("fax"),
    WEB_FEED("feed"),
    FILE("file"),
    FILESYSTEM("filesystem"),
    FINGER("finger"),
    FISH("fish"),
    FM("fm"),
    FTP("ftp"),
    GEMINI("gemini"),
    GEO("geo"),
    GADU_GADU("gg"),
    GIT("git"),
    GIZMO_5("gizmoproject"),
    NAME_RESOLUTION_PROTOCOL("go"),
    GOPHER("gopher"),
    GOOGLE_TALK("gtalk"),
    H_323("h323"),
    MICROSOFT_WINDOWS_HELP_SUPPORT_CENTER("hcp"),
    HTTP("http"),
    HTTPS("https"),
    INTER_ASTERISK_EXCHANGE("iax"),
    ICAP("icap"),
    ICON("icon"),
    INSTANT_MESSAGING("im"),
    IMAP("imap"),
    INFORMATION_ASEETS("info"),
    INTERNET_OF_THINGS("iotdisco"),
    IPN("ipn"),
    INTERNET_PRINTING_PROTOCOL("ipp"),
    INTERNET_PRINTING_PROTOCOL_OVER_HTTPS("ipps"),
    INTERNET_RELAY_CHAT("irc"),
    INTERNET_RELAY_CHAT_IPV6("irc6"),
    SECURE_INTERNET_RELAY_CHAT("ircs"),
    INTERNET_REGISTRY_INFO_SERVICE("iris"),
    INTERNET_REGISTRY_INFO_SERVICE2("iris.beep"),
    INTERNET_REGISTRY_INFO_SERVICE3("iris.xpc"),
    INTERNET_REGISTRY_INFO_SERVICE4("iris.xpcs"),
    INTERNET_REGISTRY_INFO_SERVICE5("iris.lws"),
    ITUNE_MUSIC_STORE("itms"),
    JABER("jabber"),
    JAVA_ARQUIVE("jar"),
    JAVA_MESSAGE_SERVICE("jms"),
    KEYPARC("keyparc"),
    LSAT_FM("lastfm"),
    LDAP("ldap"),
    SECURE_LDAP("ldaps"),
    MAGNET_LINKS("magnet"),
    MAIL_SERVER("mailserver"),
    STMP_MAIL_ADDRESS("mailto"),
    MAP_LINKS("maps"),
    GOOGLE_PLAY_STORE("market"),
    MAIL_MESSAGE("message"),
    SMTP_MIME_PARTS("mid"),
    WINDOWS_STREAMING_MEDIA("mms"),
    MODEM("modem"),
    MICROSOFT_WINDOWS_HELP_SUPPORT_CENTER_FROM_VISTA_LATER("ms-help"),
    WINDOWS_SETTINGS_APPLICATION("ms-settings"),
    WINDOWS_AIRPLANE_MODE_SETTINGS("ms-settings-airplanemode"),
    WINDOWS_BLUETOOTH_SETTINGS("ms-settings-bluetooth"),
    WINDOWS_CAMERA_SETTINGS("ms-settings-camera"),
    WINDOWS_CELLULAR_SETTINGS("ms-settings-cellular"),
    WINDOWS_CLOUD_SETTINGS("ms-settings-cloudstorage"),
    WINDOWS_MAIL_SETTINGS("ms-settings-emailandaccounts"),
    WINDOWS_LANGUAGE_SETTINGS("ms-settings-language"),
    WINDOWS_LOCATION_SETTINGS("ms-settings-location"),
    WINDOWS_LOCK_SETTINGS("ms-settings-lock"),
    WINDOWS_NFC_SETTINGS("ms-settings-nfctransactions"),
    WINDOWS_NOTIFICATION_SETTINGS("ms-settings-notifications"),
    WINDOWS_POWER_SETTINGS("ms-settings-power"),
    WINDOWS_PRIVACY_SETTINGS("ms-settings-privacy"),
    WINDOWS_PROXIMITY_SETTINGS("ms-settings-proximity"),
    WINDOWS_SCREEN_ROTATION_SETTINGS("ms-settings-screenrotation"),
    WINDOWS_WIFI_SETTINGS("ms-settings-wifi"),
    WINDOWS_WORKPLACE_SETTINGS("ms-settings-workplace"),
    WINDOWS_LIVE_MESSENGER("msnim"),
    MESSAGE_SESSION_RELAY("msrp"),
    MESSAGE_SESSION_RELAY2("msrps"),
    MESSAGE_TRACKING("mtqp"),
    MUMBLE("mumble"),
    MAILBOX_UPDATE("mupdate"),
    APACHE_MAVEN("mvn"),
    USENET_NEWS("news"),
    NFS("nfs"),
    NAMING_THINGS("ni"),
    NAMING_THINGS2("nih"),
    USENET_NNTP("nntp"),
    LOTUS_NOTES("notes"),
    OID("oid"),
    OPAQUE_LOCK_TOKEN("opaquelocktoken"),
    OPEN_PGP_PK("openpgp4fpr"),
    PACK("pack"),
    HP_WEB_OS("palm"),
    MAC_PAPARAZZI("paparazzi"),
    TARGET_FOR_PAYMENTS("payto"),
    PKCS_11("pkcs11"),
    ECLIPSE_PLATFORM_RESOURCES("platform"),
    MAIL_POP_3("pop"),
    COMMON_PROFILE_FOR_PRESENCE("pres"),
    PROSPERO_DIR("prospero"),
    FOXY_PROXY("proxy"),
    PSYC("psyc"),
    FILE_SYSTEM_QUERY("query"),
    REDIS_DB("redis"),
    REDIS_DB2("rediss"),
    RESOURCE_LOCATION_AND_DISCOVERY("reload"),
    INTERNET_EXPLORER_ERROR_DISPLAYING("res"),
    RESOURCE_ALIAS_MAPPING("resource"),
    JAVA_RMI_REGISTRY("rmi"),
    RSYNC("rsync"),
    REAL_TIME_MEDIA_FLOW("rtmfp"),
    REAL_TIME_MESSAGE("rtmp"),
    REAL_TIME_STREAMING("rtsp"),
    S3_BUCKET("s3"),
    SECONDLIFE("secondlife"),
    SERVICE("service"),
    MEDIA_RESOUCE_CONTROL("session"),
    SSH_FTP("sftp"),
    SOCIAL_GRAPH_NODE_MAPPER("sgn"),
    SMART_HEALTH_CARD("shc"),
    SECURE_HTTP("shttp"),
    MANGASIEVE("sieve"),
    SESSION_INITIATION("sip"),
    SECURE_SESSION_INITIATION("sips"),
    SAMBA("smb"),
    SMS("sms"),
    NNTP_OVER_TLS("snews"),
    SIMPLE_NETWORK_MANAGEMENT("snmp"),
    SOAP_BEEP("soap.beep"),
    SOAP_BEEP2("soap.beeps"),
    SOLDAT("soldat"),
    SPOTIFY("spotify"),
    SECURE_SHELL("ssh"),
    STEAM("steam"),
    SESSION_TRAVERSAL_UTILITY("stun"),
    SUBVISION("svn"),
    TAG("tag"),
    TEAM_SPEAK("teamspeak"),
    TELEPHONE("tel"),
    TELNET("telnet"),
    TRIVIAL_FTP("tftp"),
    THINGS("things"),
    THIS_MESSAGE("thismessage"),
    INTERACTIVE_EMULATION("tn3270"),
    TRANSACTION_INTERNET("tip"),
    TRAVERSAL_USING_RELAYS_NAT("turn"),
    TRAVERSAL_USING_RELAYS_NAT2("turns"),
    TV_BROADCAST("tv"),
    UDP_BITTORRENT("udp"),
    UDP_MPEG_TRANSPORT("udp"),
    UNREAL_SERVERS("unreal"),
    UNIFORM_RESOURCE_NAMES("urn"),
    UT_2004_SERVER("ut2004"),
    VERSATILE_MULTIMEDIA_INTERFACE("vemmi"),
    VENTRILO_SERVER("ventrilo"),
    VIDEOTEX("videotex"),
    CODE_WEB_PAGE("view-source"),
    VIRTUAL_NETWORK_COMPUTING("vnc"),
    WIDE_AREA_INFORMATION_SERVER("wais"),
    ICALENDAR("webcal"),
    WEB_SOCKET("ws"),
    WEB_SOCKET2("wss"),
    WHAT_YOU_CACHE_IS_WHAT_YOU_GET("wyciwyg"),
    XCON("xcon"),
    XCON_USER_ID("xcon-userid"),
    XFIRE_SERVER("xfire"),
    XML_RPC_BEEP("xmlrpc.beep"),
    XML_RPC_BEEP2("xmlrpc.beeps"),
    XMPP("xmpp"),
    EXTENSIBLE_RESOURCE_IDENTIFIER("xri"),
    YAHOO_INSTANT_MESSAGING("ymsgr"),
    Z39_50_INFO("z39.50"),
    Z39_50_INFO_RETRIEVAL("z39.50r"),
    Z39_50_INFO_SESSION("z39.50s");

    private final String scheme;

    URISchemes(final String scheme) {
        this.scheme = scheme;
    }

    public static Boolean isScheme(String scheme){

        // Check the most common protocols before looping through ALL protocols.
        if(scheme.equals(HTTP.getScheme()) || scheme.equals(HTTPS.getScheme()) || scheme.equals(SECURE_SHELL.getScheme())
        || scheme.equals(FTP.getScheme()) || scheme.equals(JDBC.getScheme())){
            return true;
        }
        // Loop through the values.
        return Arrays.stream(URISchemes.values())
                .anyMatch(s -> s.getScheme().equals(scheme.trim().toLowerCase()));
    }

    public String getScheme() {
        return scheme;
    }
}
